# Generated by Django 4.1.9 on 2023-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feedback_govuk', '0002_alter_feedback_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='issues',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
