# Generated by Django 4.1.9 on 2023-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feedback_govuk', '0003_feedback_activities_feedback_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='activities',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='issues',
            field=models.CharField(default='', max_length=200),
        ),
    ]
